### PR TITLE
Add helm timeout configurable

### LINKED ISSUE #14: Feature request: timeout option
Would be it possible to add timeout option so we can increase default one which is 5m?

Thanks

### PR DESCRIPTION
**Pull request by Babbleshack**
Adds timeout configurable

closes #14

### CODE REVIEW

**Comment by Babbleshack** [comment]
@yves-vogl are there any other changes you might need before this can be merged?

**Comment by yves-vogl** [comment]
Thank you for your work!
As you maybe can see I’ve not much time to review and merge changes. I’ll try to get back to this soon.

But as we are talking - are you interested in being a maintainer for this repo?

Regards
Yves

**Comment by yves-vogl** [comment]
Let me review the pending issue tommorrow, do some housekeeping. After that I'll add you as maintainer and share contact information with you so that we can team up.Would this work for you?Thank you so far - I really appreciate this!On 29. May 2024, at 22:14, Dominic Lindsay ***@***.***> wrote:﻿
Sure that can work. How do we go forward with this?

-------- Original Message --------

**Comment by Babbleshack** [comment]
Yer that works.  I use this for work so I have a good reason to maintain it.

No problem. Thanks for the opportunity.

**Comment by yves-vogl** [comment]
I've merged your PR. I'll now do some housekeeping (we've holidays in NRW, Germany today).
After that I'll get in touch with you so that we can find a way to communicate. 

Thank you - teamwork is simply the best <3

**Comment by Babbleshack** [comment]
Awesome! I saw you pushed a new release to docker hub too. Thank you!

Enjoy your holiday, ill catch up with you when you return.

**Comment by yves-vogl** [comment]
You're welcome :-)


Releasing to dockerhub ist automated.
I added you in LinkedIn by the way. And set you up as collab on Bitbucket. If you tell me your DockerHub name, I'll add you there as well.

**Pull request merged**
