### PR TITLE
Add support for "--wait" switch

### PR DESCRIPTION
**Pull request by maxmarcon**
Hi! How do you feel about adding support for the `--wait` switch in helm?

### CODE REVIEW

**Comment by yves-vogl** [comment]
Why not ❤️🥲

**Comment by maxmarcon** [comment]
Thank for merging so quickly. Being able to use "wait" would help me in my deployment.

**Comment by yves-vogl** [comment]
I'll release a new container version soon.

**Comment by maxmarcon** [comment]
Thanks!!! 👏

**Pull request merged**
